const piiNormalizationService = require('../services/piiNormalizationService');
const allowlistService = require('../services/allowlistService');

/**
 * Leakage Analyzer
 * Classifies rescan candidate entity findings into Categories A-D:
 * CATEGORY A — EXPECTED_SYNTHETIC_ENTITY (Synthetic replacement generated by replacement engine)
 * CATEGORY B — CONFIRMED_LEAK (Original PII text or its normalized value still present)
 * CATEGORY C — NEW_UNINTENDED_PII (Unintended sensitive value generated)
 * CATEGORY D — SCANNER_FALSE_POSITIVE (Non-PII term flagged by detectors)
 */
class LeakageAnalyzer {
  /**
   * Classifies a rescan entity finding
   * @param {Object} candidateEntity - Rescan entity ({ type, text, start, end, normalizedValue })
   * @param {Array<Object>} originalEntities - Original PII entities list before redaction
   * @param {Map|Set} syntheticReplacementsSet - Set of expected synthetic replacement strings
   * @param {Map|Set} originalPiiNormalizedSet - Set of original normalized PII strings
   * @returns {Object} Classified finding metadata
   */
  classifyFinding(candidateEntity, originalEntities, syntheticReplacementsSet, originalPiiNormalizedSet) {
    const text = candidateEntity.text ? candidateEntity.text.trim() : '';
    const normVal = piiNormalizationService.normalize(candidateEntity.type, text);

    // 0. Check for CATEGORY D — SCANNER_FALSE_POSITIVE (Allowlisted non-PII terms)
    if (allowlistService.isAllowlisted(candidateEntity.type, text)) {
      return {
        category: 'SCANNER_FALSE_POSITIVE',
        expectedSynthetic: false,
        severity: 'LOW',
        description: 'Allowlisted non-PII statutory/regulatory term flagged by detector'
      };
    }

    // 1. Check for CATEGORY A — EXPECTED_SYNTHETIC_ENTITY (Synthetic replacement generated by engine)
    if (syntheticReplacementsSet.has(text) || syntheticReplacementsSet.has(normVal) || syntheticReplacementsSet.has(text.toLowerCase())) {
      return {
        category: 'EXPECTED_SYNTHETIC_ENTITY',
        expectedSynthetic: true,
        severity: 'LOW',
        description: 'Detector identified an intentionally generated synthetic replacement entity'
      };
    }

    // 2. Check for CATEGORY B — CONFIRMED_LEAK (Original PII text or normalized key still present)
    if (originalPiiNormalizedSet.has(text) || originalPiiNormalizedSet.has(normVal) || this.matchesOriginalEntityText(text, originalEntities)) {
      return {
        category: 'CONFIRMED_LEAK',
        expectedSynthetic: false,
        severity: 'CRITICAL',
        description: 'Original PII text or its normalized comparison key was detected in redacted output'
      };
    }

    // 3. Check for CATEGORY C — NEW_UNINTENDED_PII vs CATEGORY D — SCANNER_FALSE_POSITIVE
    if (['CREDIT_CARD', 'SSN', 'EMAIL', 'PHONE', 'IP_ADDRESS'].includes(candidateEntity.type)) {
      return {
        category: 'NEW_UNINTENDED_PII',
        expectedSynthetic: false,
        severity: 'HIGH',
        description: 'Detector identified an unlisted deterministic PII entity in redacted text'
      };
    }

    return {
      category: 'SCANNER_FALSE_POSITIVE',
      expectedSynthetic: false,
      severity: 'LOW',
      description: 'NER detector flagged a non-PII term in redacted output'
    };
  }

  /**
   * Helper to check if text exactly matches any original entity's raw or normalized text
   * @param {string} text 
   * @param {Array<Object>} originalEntities 
   * @returns {boolean}
   */
  matchesOriginalEntityText(text, originalEntities) {
    if (!text || !originalEntities) return false;
    const lowerText = text.toLowerCase();

    return originalEntities.some(orig => {
      if (!orig.text) return false;
      if (allowlistService.isAllowlisted(orig.type, orig.text)) return false;
      const origLower = orig.text.toLowerCase().trim();
      return origLower === lowerText;
    });
  }
}

module.exports = new LeakageAnalyzer();
